site_name: Odoo Developer Kit
site_description: A Flutter-like developer toolkit for Odoo developers.
site_url: https://odoo-developer-kit.github.io/odoo-developer-kit/
repo_url: https://github.com/odoo-developer-kit/odoo-developer-kit
repo_name: odoo-developer-kit/odoo-developer-kit

theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - Doctor: doctor.md
  - Create: create.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
