name: Docs

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install documentation dependencies
        run: python -m pip install mkdocs mkdocs-material

      - name: Build docs
        run: mkdocs build --strict
